name: 'Setup Build Environment'
description: 'Common setup for CI and Release builds'

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '22'
  pnpm-version:
    description: 'pnpm version'
    required: false
    default: '9'
  rust-cache-shared-key:
    description: 'Shared key for Rust cache'
    required: true
  rust-cache-save:
    description: 'Whether to save Rust cache'
    required: false
    default: 'false'
  install-tauri-deps:
    description: 'Install Tauri Linux dependencies'
    required: false
    default: 'false'
  rust-targets:
    description: 'Additional Rust targets to install'
    required: false
    default: ''
  rust-components:
    description: 'Rust components to install (e.g., rustfmt, clippy)'
    required: false
    default: ''
  create-sidecar-placeholders:
    description: 'Create placeholder sidecars for CI (skip real downloads)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Restore file timestamps for cache
      uses: chetan/git-restore-mtime-action@v2

    - name: Cache and install Tauri dependencies (Linux)
      if: inputs.install-tauri-deps == 'true' && runner.os == 'Linux'
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: build-essential libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        version: 1.0

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.rust-targets }}
        components: ${{ inputs.rust-components }}

    - name: Cache Cargo
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: src-tauri
        prefix-key: v3
        shared-key: ${{ inputs.rust-cache-shared-key }}
        cache-on-failure: true
        cache-all-crates: true
        save-if: ${{ inputs.rust-cache-save }}

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --ignore-scripts
      env:
        HUSKY: '0'

    - name: Create placeholder sidecars
      if: inputs.create-sidecar-placeholders == 'true'
      shell: bash
      run: |
        mkdir -p src-tauri/binaries/chrome-headless-shell-x86_64-unknown-linux-gnu
        touch src-tauri/binaries/chrome-headless-shell-x86_64-unknown-linux-gnu/chrome-headless-shell
        touch src-tauri/binaries/node-x86_64-unknown-linux-gnu
        mkdir -p src-tauri/resources/lighthouse-sidecar
        echo '{}' > src-tauri/resources/lighthouse-sidecar/package.json
